### ISSUE TITLE
'Provider' required when registering a new package source

### ISSUE THREAD

**Issue by ethanbergstrom** [AnyPackage/AnyPackage#1]
None of the other cmdlets require it, but I wasn't sure if that requirement was intended or not, so thought I'd mention it.

https://github.com/AnyPackage/AnyPackage/blob/5024b3b06b96ceebffb7c4796fc3af461b3207bf/src/AnyPackage/Commands/RegisterPackageSourceCommand.cs#L42-L49

**Comment by ThomasNieto** [comment]
Yes, that is intended so there is no ambiguity of which package provider should be called.
