### ISSUE TITLE
Unable to return any other packages other than posh-git and AnyPackage

### ISSUE THREAD

**Issue by scottharman** [anypackage/anypackage#254]
Hi team - I'm unable to query any packages on the system using AnyPackage running PS 7.4.6 and AnyPackage 0.8.0
```
Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
AnyPackage                     0.8.0            https://www.powershellgallery.c… PowerShellGet
posh-git                       1.1.0            https://www.powershellgallery.c… PowerShellGet
```
Specifically I'm looking to query installed Programs and WinGet packages, but I'm not able to return anything other than the two packages above.
```
$PsVersionTable

Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Any thoughts on how to resolve this?

**Comment by ThomasNieto** [comment]
Can you run the following commands and post the output here?

```powershell
Get-Module

Get-PackageProvider
```

**Comment by scottharman** [comment]
Yeah sure - interestingly, after a reboot I get no results for get-package until I run import-module anypackage.

get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.8.0                 AnyPackage                          {Find-Package, Get-Package, Get-PackageProvider, …
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variable, Compare-Ob…
Script     1.4.8.1               PackageManagement                   {Find-Package, Find-PackageProvider, Get-Package,…
Script     2.2.5                 PowerShellGet                       {Find-Command, Find-DscResource, Find-Module, Fin…
Script     2.3.5                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

get-package

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
AnyPackage                     0.8.0            https://www.powershellgallery.c… PowerShellGet
posh-git                       1.1.0            https://www.powershellgallery.c… PowerShellGet

After reboot:

get-module

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.8.0                 AnyPackage                          {Find-Package, Get-Package, Get-PackageProvider, …
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Content, Clear-Content, Clear-Item, Clear-It…
Script     2.3.5                 PSReadLine                          {Get-PSReadLineKeyHandler, Get-PSReadLineOption, …

get-package
Get-Package: No package providers available.

**Comment by ThomasNieto** [comment]
Importing the `AnyPackage` module doesn't do anything on its own. You have to import the package provider module. In your case you want Windows Programs and WinGet.

```powershell
Import-Module AnyPackage.Programs
Import-Module AnyPacakge.WinGet
```

**Comment by scottharman** [comment]
Hey @ThomasNieto - I get an error about the modules:

```
PS C:\Users\scott> Import-Module AnyPackage.Programs
Import-Module: The specified module 'AnyPackage.Programs' was not loaded because no valid module file was found in any module directory.
PS C:\Users\scott> Import-Module AnyPackage.WinGet
Import-Module: The specified module 'AnyPackage.WinGet' was not loaded because no valid module file was found in any module directory.
```

**Comment by ThomasNieto** [comment]
Did you install the modules from the PowerShell gallery?

**Comment by scottharman** [comment]
Yes I did - however I've just run `Install-Module AnyPackage.Programs` and `Install-Module AnyPackage.WinGet` and they are ow listed in Get-Package, but they remain unqueryable

```
PS C:\Users\scott> Get-Package -v
VERBOSE: Suppressed Warning Unknown category for 'NuGet'::'GetDynamicOptions': 'Provider'

Name                           Version          Source                           ProviderName
----                           -------          ------                           ------------
AnyPackage                     0.8.0            https://www.powershellgallery.c… PowerShellGet
AnyPackage.Programs            0.3.2            https://www.powershellgallery.c… PowerShellGet
AnyPackage.WinGet              0.0.7            https://www.powershellgallery.c… PowerShellGet
Cobalt                         0.4.0            https://www.powershellgallery.c… PowerShellGet
posh-git                       1.1.0            https://www.powershellgallery.c… PowerShellGet
```

**Comment by ThomasNieto** [comment]
Remove these two modules from your session, after that import the modules in my previous post.

```powershell
Remove-Module PowerShellGet, PackageManagement
```

**Comment by scottharman** [comment]
Yes that now works - thank you.
```
Remove-Module PowerShellGet, PackageManagement
Import-Module AnyPackage.WinGet
Import-Module AnyPackage.Programs

Get-Package
Name                                     Version         Source               Provider
----                                     -------         ------               --------
Bitwarden                                2024.12.1                            Programs
BatteryBar (remove only)                                                      Programs
Beyond Compare 5.0.4                     5.0.4.30422     C:\Program Files\Be… Programs
```

So after a couple more tests, I need to explitly run that series of commands every time I wish to I wish to use Get-Package.

Will see if it's still successful after adding to my profile, as Install-Module -Force seems to be overridden by the default packagemanager

**Comment by ThomasNieto** [comment]
Good to hear.

You only need to run those remove commands if `PackageManagement` gets imported which is done by `PowerShellGet`. Since those two modules are deprecated I recommend using `PSResourceGet` and there is an AnyPackage provider for that `AnyPackage.PSResourceGet`.
